### ISSUE TITLE
multiplying activities in v201 dashboard

### ISSUE THREAD

**Issue by SJ-bond** [younginnovations/aidstream-v201-migration#19]
hello, see screenshot below - we have 5 activities in the Bond AidStream account but alert message mentions 8! 
![aidstream multiplying activities message](https://cloud.githubusercontent.com/assets/8158574/9738400/39a58462-5643-11e5-9efa-cdb4c00e95a1.png)

**Comment by anjesh** [comment]
Hi Sarah,

I see you have reported the problem v201 but i am writing about the current aidstream.org. The problem is similar in both. 

I think the problem appeared because the publishing-type is changed from unsegmented to segmented. Here's what i think happened. 
1. You published the activities in unsegmented - hence bond-activities.xml file, containing 4 activities.
2. You updated the activities, 3 are in draft and 1 still in published.
3. You changed the unsegmented to segmented.
4. You republished the activities - hence bond-gb.xml, containing 1 activity.

Currently AidStream doesn't delete the file from registry, assuming it might have been used somewhere. Infact I don't remember if registry-api allows deletion or not. It's upto the user to delete the files manually from the registry interface. 

The number you should be seeing in the dashboard is 5 because AidStream maintains the previous file count as well (we will fix this in new AidStream) 
![image](https://cloud.githubusercontent.com/assets/120488/9779443/5eaa97e4-579b-11e5-8d09-4013e00b0ea0.png)
However it was 8, i assume there must have been some mistakes in Registry side.

Till yesterday, bonds-gb.xml was showing 4 activities, but now it's showing up 1 (which should have been the case)

![image](https://cloud.githubusercontent.com/assets/120488/9779453/80b2571e-579b-11e5-89b7-2f0863c989f1.png)

For now, we will fix the number to 1 in dashboard, you will have to delete the bonds-activities.xml file directly from the Registry.
